version: '3.6'
services:
  queue:
    image: rabbitmq:3.7-management
    hostname: "rabbit"
    labels:
      NAME: "rabbit"
    env_file:
      - ./env/rabbitmq.env
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    
  db:
    image: postgres:11.2
    ports:
      - "5432:5432"
    env_file:
      - ./env/pg.env
    volumes:
      - ./volumes/pg:/var/lib/postgresql/data
  
  migration:
    image: amacneil/dbmate
    env_file:
      - ./env/pg.env
    volumes:
      - ./migrations:/db/migrations
    command: up