version: '3.6'
services:
  queue:
    image: rabbitmq:3.7-management
    hostname: "rabbit"
    labels:
      NAME: "rabbit"
    env_file:
      - ./env/rabbitmq.env
    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    
  db:
    image: postgres:11.2
    ports:
      - "5432:5432"
    env_file:
      - ./env/pg.env
    volumes:
      - ./volumes/pg:/var/lib/postgresql/data
  
  migration:
    image: amacneil/dbmate
    env_file:
      - ./env/pg.env
    volumes:
      - ./consumer/migrations:/db/migrations
    command: up

  producer:
    image: filatovw/fc-producer:latest
    build:
      context: ./
      dockerfile: ./producer/Dockerfile
    env_file:
      - ./env/producer.env
    volumes:
      - ./producer/data:/data
    command: producer -queue-addr queue:5672 -file /data/data_1000.csv
    
  consumer:
    image: filatovw/fc-consumer:latest
    build:
      context: ./
      dockerfile: ./consumer/Dockerfile
    env_file:
      - ./env/consumer.env
    command: consumer -queue-addr queue:5672 -db-host db -db-port 5432